### ISSUE TITLE
Diff of New Files

### ISSUE THREAD

**Issue by lcnittl** [lcnittl/DMFO#4]
Currently throws an error:
```
PS C:\...\repo> git diff --staged
Resolve-Path : Cannot find path 'C:\...\repo\nul' because it does not exist.
At C:\...\DMFO\dmfo-diff.ps1:28 char:18
+     $FileName = (Resolve-Path $FileNames[$key]).Path
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\...\repo\nul:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

fatal: external diff died, stopping at NewFile.pptx
```

Should open the newly added file without any comparison.

**Comment by lcnittl** [comment]
```py
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lcnittl\.local\bin\dmfo.exe\__main__.py", line 4, in <module>
  File "c:\users\lcnittl\.local\pipx\venvs\dmfo\lib\site-packages\dmfo\__main__.py", line 10, in <module>
    sys.exit(main())
  File "c:\users\lcnittl\.local\pipx\venvs\dmfo\lib\site-packages\dmfo\__init__.py", line 258, in main
    ret = dmfo.files.preproc(filedata_map=filedatamap)
  File "c:\users\lcnittl\.local\pipx\venvs\dmfo\lib\site-packages\dmfo\files\__init__.py", line 17, in preproc
    filename = filedata_map[alias].name.resolve(strict=True)
  File "c:\program files\python39\lib\pathlib.py", line 1204, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "c:\program files\python39\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 87] The parameter is incorrect: 'nul'
fatal: external diff died, stopping at SI.docx```
